# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - circle-ci
      
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .

      - run:
          name: run tests with PyTest
          command: |
            . venv/bin/activate
            pip install .[testing]
            pytest

      - run:
          name: linting with Flake8
          command: |
            . venv/bin/activate
            pip install .[linting]
            # stop the build if there are Python syntax errors or undefined names 
            flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
            # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide      
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - store_artifacts:
          path: test-reports
          destination: test-reports
