# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      
      # Take advantage of latest cache of dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo pip install -r requirements.txt

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache 

      - run:
          name: Run linter
          command: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 datascroller --count --select=E901,E999,F821,F822,F823 \
              --show-source --statistics
            # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide      
            flake8 datascroller --count --exit-zero --max-complexity=10 \
              --max-line-length=127 --statistics

      - run:
          name: Run Tests
          command: |
            pytest test/

      - run:
          name: init .pypirc
          command: |
            python create_pypirc.py $PYPI_USERNAME $PYPI_PASSWORD > .pypirc
            #echo -e "[pypi]" >> ~/.pypirc
            #echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            #echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
            
      - deploy:
          name: Upload to PyPi
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              twine upload --repository testpypi dist/*
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              twine upload dist/*
            fi
